version: '3.8'
services:
  movies:
    image: kiran224691/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: kiran224691/paytmrecharge:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: kiran224691/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

